site_name: Nimble User Guide
repo_url: https://github.com/nim-lang/nimble
repo_name: nim-lang/nimble

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


use_directory_urls: false

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.superfences


nav:
  - Home:
    - 'index.md'
    - 'install-nimble.md'

  - Use existing packages:
    - 'use-packages.md'

  - Create Nimble packages:
    - 'create-packages.md'

  - Nimble develop workflow:
    - 'workflow.md'

  - Misc:
    - 'package-types.md'
    - 'config.md'
    - 'nimble-reference.md'
    - 'folder-structure.md'
    - 'troubleshooting.md'
